const gatewayURL = 'https://dev-gateway.bengaluruairport.com'
const serverURL = 'https://dev-gateway.bengaluruairport.com' + '/airportportal';
// const serverURL = 'http://localhost:7009';
const config = {
  api: {
    '': '-------------------------------AUTH----------------------------------------',
    generateOtp: `${gatewayURL}/login/otp`,
    login: `${gatewayURL}/login/local`,
    // loginWithOtp: `${airportURL}/api/loginWithOtp`,
    // loginWithPwd: `${airportURL}/api/loginWithPwd`, 
    updatePassword: `${serverURL}/api/updatePwd`,
    // logout: `${airportURL}/api/shoplogout`,
    logout: `${gatewayURL}/logout`,
    '': '-------------------------------Concessioners----------------------------------------',
    getConcessionerList: `${serverURL}/api/getConcessionerList`,
    getAllConcessioners: `${serverURL}/api/getAllConcessioners`,
    deleteConcessioner: `${serverURL}/api/deleteConcessioner`,
    tendersList: `${serverURL}/api/tendersList`,
    getTendersList:`${serverURL}/api/getTender/{{userId}}`,
    newTender: `${serverURL}/api/addTender`,
    contactUsList: `${serverURL}/api/ContactUsList`,
    feedbackList: `${serverURL}/api/feedbackList`,
    getFeedback: `${serverURL}/api/getfeedback/{{userId}}`,
    lostandFoundList: `${serverURL}/api/lostandfoundList`,
    getLostandFound: `${serverURL}/api/getlostandfound/{userId}`,
    userRegistrationList: `${serverURL}/api/userRegistration`,
    newContactUs: `${serverURL}/api/addContactUs`,
    getEachContactUs:`${serverURL}/api/getContactUs/{{userId}}`,
    '':
      '-------------------------------Concessioners => Concessioner----------------------------------------',
    setConcessionerDetail: `${serverURL}/api/setConcessionerDetail`,
    getConcessionerDetail: `${serverURL}/api/getConcessionerDetail`,  
    '':"---------------------------Permission -------------------------------------------------",
    getAllPermissionList:`${serverURL}/api/getPermissionsList`,
    addUpdatePermission: `${serverURL}/api/addNewPermission`,
    deletePermission:`${serverURL}/api/deletePermission`,
    getSinglePermission: `${serverURL}/api/getSinglePermission`,
    '':"-----------------------Asset Detail-----------------------------------------------",
    assetDetailList:`${serverURL}/api/assetDetailList`,
    assetTypeList:`${serverURL}/api/getAssetTypeList`,
    addAssetDetail:`${serverURL}/api/addNewAsset`,
    getAssetDetail:`${serverURL}/api/getAssetDetail`,
    deleteAssetDetail:`${serverURL}/api/deleteAssetDetail`,
    '': '-------------------------------Concessioners => Contract----------------------------------------',
    setConcessionerContract: `${serverURL}/api/setConcessionerContract`,
    getConcessionerContract: `${serverURL}/api/getConcessionerContract`,
    deleteConcessionerContract: `${serverURL}/api/deleteConcessionerContract`,
    '': '-------------------------------Concessioners => Contact----------------------------------------',
    setConcessionerContact: `${serverURL}/api/setConcessionerContact`,
    getConcessionerContact: `${serverURL}/api/getConcessionerContact`,
    deleteConcessionerContact: `${serverURL}/api/deleteConcessionerContact`,
    '': '-------------------------------Concessioners => Address----------------------------------------',
    setConcessionerAddress: `${serverURL}/api/setConcessionerAddress`,
    getConcessionerAddress: `${serverURL}/api/getConcessionerAddress`,
    deleteConcessionerAddress: `${serverURL}/api/deleteConcessionerAddress`,
    '': '-------------------------------Concessioners => Tax----------------------------------------',
    setConcessionerTax: `${serverURL}/api/setConcessionerTax`,
    getConcessionerTax: `${serverURL}/api/getConcessionerTax`,
    '': '-------------------------------STORES----------------------------------------',
    getStoreList: `${serverURL}/api/getStoreList`,
    deleteStore: `${serverURL}/api/deleteStore`,
    '': '-------------------------------STORES -> STORE-------------------------------',
    getCategoryList: `${serverURL}/api/getCategoryList`,
    setStoreDetail: `${serverURL}/api/setStoreDetail`,
    getStoreDetail: `${serverURL}/api/getStoreDetail`,
    '': '-------------------------------STORES -> IMAGE-------------------------------',
    getStoreImage: `${serverURL}/api/getStoreImage`,
    setStoreImage: `${serverURL}/api/setStoreImage`,
    '': '-------------------------------STORES -> LOCATION----------------------------',
    getAirportTerminals: `${serverURL}/api/getTerminals`,
    getStoreLocation: `${serverURL}/api/getStoreLocation`,
    setStoreLocation: `${serverURL}/api/setStoreLocation`,
    '': '-------------------------------STORES -> CONTACT-----------------------------',
    getStoreContacts: `${serverURL}/api/getStoreContact`,
    addUpdateStoreContact: `${serverURL}/api/setStoreContact`,
    deleteStoreContact: `${serverURL}/api/deleteStoreContact`,
    '': '-------------------------------STORES -> MANAGE CATEGORY-----------------------------',
    categoryMasterListApi: `${serverURL}/api/getShopCategoryMasterList`,
    getCategoryMasterDetail: `${serverURL}/api/getShopCategoryMasterDetail`,
    setCategoryMasterDetail: `${serverURL}/api/setShopCategoryMasterDetail`,
    deleteCategoryMaster: `${serverURL}/api/deleteShopCategoryMaster`,
    '': '-------------------------------PRODUCTS--------------------------------------',
    downloadTemplate: `${serverURL}/api/downloadTemplateFile`,
    uploadProductCategory: `${serverURL}/api/uploadProductCategory`,
    downloadFailedProductCategoryFile: `${serverURL}/api/downloadFailedProductCategoryFile`,
    '': '-------------------------------PRODUCTS -> CATALOGUE-------------------------',
    getProductCategories: `${serverURL}/api/productCategoryList`,
    updateProductCategory: `${serverURL}/api/editStoreProductCategory`,
    deleteProductCategory: `${serverURL}/api/deleteStoreProductCategory`,
    createProductCategories: `${serverURL}/api/setStoreProductCategory `,
    uploadProductCatalogue: `${serverURL}/api/uploadProductCatalogue`,
    downloadFailedProductCatalogue: `${serverURL}/api/downloadFailedProductCatalogueFile`,
    getCatalogueUploadHistory: `${serverURL}/api/archivedCatalogueFiles`,
    downloadArchivedCatalogueFile: `${serverURL}/api/downloadArchivedCatalogueFile`,
    '': '-------------------------------PRODUCTS -> PRICE-----------------------------',
    uploadPriceData: `${serverURL}/api/uploadPriceData`,
    downloadFailedPriceData: `${serverURL}/api/downloadFailedPriceDataFile`,
    getPriceUploadHistory: `${serverURL}/api/archivedPriceDataFiles`,
    downloadArchivedPriceFile: `${serverURL}/api/downloadArchivedPriceDataFile`,
    '': '-------------------------------PRODUCTS -> INVENTORY-------------------------',
    uploadInventoryData: `${serverURL}/api/uploadInventoryData`,
    downloadFailedInventoryData: `${serverURL}/api/downloadFailedInventoryDataFile`,
    getInventoryUploadHistory: `${serverURL}/api/archivedInventoryDataFiles`,
    downloadArchivedInventoryFile: `${serverURL}/api/downloadArchivedInventoryDataFile`,
    '': '-------------------------------ADBANNERS-------------------------------------',
    getBanners: `${serverURL}/api/getBanners`,
    createBanner: `${serverURL}/api/createBanner`,
    updateBanner: `${serverURL}/api/updateBanner`,
    deleteBanner: `${serverURL}/api/deleteBanner`,
    getBannerDetails: `${serverURL}/api/getBannerDetails`,
    uploadImage: `${serverURL}/api/uploadImage`,
    bannerImg: `${serverURL}/bannerImg`,
    '': '-------------------------------QR CODE---------------------------------------',
    getQRCode: `${serverURL}/api/getQRCode`,
    '': '-------------------------------PARTNERS----------------------------------------',
    partnersList: `${serverURL}/api/partnersList`,
    newPartner: `${serverURL}/api/newPartner`,
    updatePartner: `${serverURL}/api/updatePartner`,
    deletePartner: `${serverURL}/api/deletePartner`,
    '': '-------------------------------PARTNERTYPE----------------------------------------',
    partnerTypeList: `${serverURL}/api/partnerTypeList`,
    newPartnerType: `${serverURL}/api/newPartnerType`,
    updatePartnerType: `${serverURL}/api/updatePartnerType`,
    deletePartnerType: `${serverURL}/api/deletePartnerType`,
    findPartnerType: `${serverURL}/api/findPartnerType`,
    '': '-------------------------------PARTNERCATEGORY----------------------------------------',
    partnerCategoryList: `${serverURL}/api/partnerCategoryList`,
    newPartnerCategory: `${serverURL}/api/newPartnerCategory`,
    updatePartnerCategory: `${serverURL}/api/updatePartnerCategory`,
    deletePartnerCategory: `${serverURL}/api/deletePartnerCategory`,
    findPartnerCategory: `${serverURL}/api/findPartnerCategory`,
    '': '-------------------------------AIRPORTGUIDE----------------------------------------',
    airportGuideList: `${serverURL}/api/airportGuideList`,
    newAirportGuide: `${serverURL}/api/newAirportGuide`,
    updateAirportGuide: `${serverURL}/api/updateAirportGuide`,
    deleteAirportGuide: `${serverURL}/api/deleteAirportGuide`,
    '': '-------------------------------BLOGS----------------------------------------',
    blogsList: `${serverURL}/api/blogsList`,
    getBlogDetail: `${serverURL}/api/getBlogDetail`,
    newBlog: `${serverURL}/api/newBlog`,
    updateBlog: `${serverURL}/api/updateBlog`,
    deleteBlog: `${serverURL}/api/deleteBlog`,
    '': '-------------------------------BLOGS CATEGORY MASTER----------------------------------------',
    blogCategoryList: `${serverURL}/api/blogCategoryList`,
    newBlogCategory: `${serverURL}/api/newBlogCategory`,
    updateBlogCategory: `${serverURL}/api/updateBlogCategory`,
    deleteBlogCategory: `${serverURL}/api/deleteBlogCategory`,
    findBlogCategory: `${serverURL}/api/findBlogCategory`,
    '': '-------------------------------NEWS BROADCAST----------------------------------------',
    newsBroadcastList: `${serverURL}/api/newsBroadcastList`,
    getNewsBroadcastDetail: `${serverURL}/api/getNewsBroadcastDetail`,
    newNewsBroadcast: `${serverURL}/api/newNewsBroadcast`,
    updateNewsBroadcast: `${serverURL}/api/updateNewsBroadcast`,
    deleteNewsBroadcast: `${serverURL}/api/deleteNewsBroadcast`,
    '': '-------------------------------CATEGORY DATA => USER ROLES----------------------------------------',
    roleList: `${serverURL}/api/roleListApi`,
    getRoleDetails: `${serverURL}/api/getRoleDetails`,
    setRoleDetails: `${serverURL}/api/setRoleDetails`,
    deleteRole: `${serverURL}/api/deleteRole`,
    '': '-------------------------------CATEGORY DATA => APP TYPE----------------------------------------',
    appTypeListApi: `${serverURL}/api/appTypeListApi`,
    getAppTypeDetails: `${serverURL}/api/getAppTypeDetails`,
    setAppTypeDetails: `${serverURL}/api/setAppTypeDetails`,
    deleteAppType: `${serverURL}/api/deleteAppType`,
    '': '-------------------------------USERS ----------------------------------------',
    userCategoryList: `${serverURL}/api/userCategoryList`,
    getUserCategoryDetails: `${serverURL}/api/getUserCategoryDetails`,
    setUserCategoryDetails: `${serverURL}/api/setUserCategoryDetails`,
    deleteUserCategory: `${serverURL}/api/deleteUserCategory`,

    userList: `${serverURL}/api/userList/{{pageno}}/{{limit}}`,
    newUser: `${serverURL}/api/newUser`,
    
    getUser: `${serverURL}/api/getUser/{{userId}}`,
    deleteUser: `${serverURL}/api/deleteUser/{{userId}}`,
    '': '-------------------------------PERMISSIONS----------------------------------------',
    getPermissions: `${gatewayURL}/gw/api/user/permissions/v2/{appType}`,
    '': '-------------------------------CATEGORY DATA => ROLE ASSET PERM MAPPING----------------------------------------',
    mappingListApi: `${serverURL}/api/roleAssetPermMappingList/{{pageno}}/{{limit}}`,
    getMappingDetails: `${serverURL}/api/getRoleAssetPermMapping/{{mappingId}}`,
    setMappingDetails: `${serverURL}/api/newRoleAssetPermMapping`,
    deleteMapping: `${serverURL}/api/deleteRoleAssetPermMapping/{{mappingId}}`,
    
  
  
  },
  ux: {
    throttleControl: 500,
  },
  appDetails: {
    appName: "airportportal"
  },
  date: {
    displayFormat: 'DD MMM, YYYY',
    timeFormat: 'HH:mm',
    dateFormat: 'DD MMM, YYYY',
  },
  auth: {},
  url: {
    serverURL,
  },
  permissionsConfig: {
    "None": 0, 
    "View": 1,
    "Edit": 2,
    "Add": 3,
    "Delete": 4
  },
  actions: [

    {
      id: 'AdminDashboard',
      display: 'Dashboard',
      subItem: [
        {
          id: 'tenders',
          display: 'Tenders',
        },
        {
          id: 'feedback',
          display: 'Feedback',
        },
        {
          id: 'lostandfoundclaims',
          display: 'Lost & Found claims',
        },
        {
          id: 'contactus',
          display: 'ContactUs',
        },
        {
          id: 'userregistration',
          display: 'User Registration',
        },
      ],
    },
    {
      id: 'concessioner',
      display: 'Concessioner',
      subItem: [
        {
          id: 'contract',
          display: 'Contract & Details',
        },
        {
          id: 'stores',
          display: 'Stores',
        },
        {
          id: 'categories',
          display: 'Category Master',
        },
      ],
    },
    {
      id: 'campaign',
      display: 'Campaign',
    },
    {
      id: 'adBanner',
      display: 'Ad Banner',
    },
    {
      id: 'partner',
      display: 'Partners',
      subItem: [
        { id: 'partners', display: 'Partners' },
        {
          id: 'partnerMaster',
          display: 'Category Master',
        },
      ],
    },
    {
      id: 'cms',
      display: 'CMS',
      subItem: [
        {
          id: 'blog',
          display: 'Blog',
        },
        {
          id: 'guidelines',
          display: 'Guidelines',
        },
        {
          id: 'newsBroadcast',
          display: 'News Broadcast',
        },
      ],
    },
    {
      id: 'user',
      display: 'Users',
      subItem: [
        {
          id: 'users',
          display: 'Users',
        },
        {
          id: 'userMaster',
          display: 'Category Master',
        },
      ],
    },
    {
      id: 'masterData',
      display: 'IAM',
      subItem: [
        {
          id: 'appType',
          display: 'App Type',
        },
        {
          id: 'userRoles',
          display: 'User Roles',
        },
        {
          id: 'technicalAssets',
          display: 'Technical Assets',
        },
        {
          id: 'roleAssetPermMapping',
          display: 'Permission Mapping',
        },
        {
          id: 'permissions',
          display: 'Permissions',
        },
      ],
    },
 
    
  ],
  filename: {
    products: {
      template: {
        catalogue: 'ProductDQtemplate.xlsx',
        dailyPriceUpdate: 'Daily Price Update.xlsx',
        inventoryManagement: 'Inventory Data.xlsx',
      },
    },
    stores: {
      template: {
        productCategory: 'Store - Product Category.xlsx',
      },
    },
  },
  tabApiMap: {
    catalogue: {
      failedFileAPI: 'downloadFailedProductCatalogue',
      uploadFileAPI: 'uploadProductCatalogue',
      historyTblAPI: 'getCatalogueUploadHistory',
      downloadFile: 'downloadArchivedCatalogueFile',
    },
    dailyPriceUpdate: {
      failedFileAPI: 'downloadFailedPriceData',
      uploadFileAPI: 'uploadPriceData',
      historyTblAPI: 'getPriceUploadHistory',
      downloadFile: 'downloadArchivedPriceFile',
    },
    inventoryManagement: {
      failedFileAPI: 'downloadFailedInventoryData',
      uploadFileAPI: 'uploadInventoryData',
      historyTblAPI: 'getInventoryUploadHistory',
      downloadFile: 'downloadArchivedInventoryFile',
    },
  },
  productCategory: {
    attributes: {
      maxAttributeCount: 20,
    },
  },
};

export default config;
